config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  
  devise_for :users, controllers: { registrations: 'registrations' }
  
  root 'login#welcome'
  
  resources :posts do
  	collection do
  		get :wear
  		get :eat
  		get :live
  		get :culture
  	end
  end

  post 'posts/wear'
  post 'posts/eat'
  post 'posts/live'
  post 'posts/culture'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/archive.rb
class Archive < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, to: :data

  validates :data, presence: true
  
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  mount_uploader :data, CkeditorAttachmentFileUploader, mount_on: :data_file_name

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, mount_on: :data_file_name

  def url_content
    url(:content)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :archiving_users, :through => :archives, class_name:"User"
  enum category: [ :wear, :eat, :live, :culture]
  enum season: [ :spring, :summer, :autumn, :winter]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :posts
  has_many :archived_posts, :through => :archives, class_name:"Post"
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

end

app/controllers/login_controller.rb
class LoginController < ApplicationController
	def welcome
	end
	
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :authenticate_user!
 	before_action :set_post, only: [ :show, :edit, :update, :destroy]
 
 	def index
 		@posts = Post.all
 	end

 	def wear
 		@posts = Post.wear
 	end

 	def eat
 		@posts = Post.eat
 	end

 	def live
 		@posts = Post.live
 	end

 	def culture
 		@posts = Post.culture
 	end

 	def show
 	end
 
 	def new
 		@post = Post.new
 	end
 
 	def create
 		@post = Post.new(post_params)
 		@post.user = current_user
 		if @post.save
 			redirect_to @post
 		else
 			render 'new'
 		end
 	end
 
 	def update
 		if @post.update(post_params)
 			redirect_to @post
 		else
 			render 'edit'
 		end
 	end
 
 	def destroy
 		@post.destroy
 		redirect_to posts_path
 	end
 
 	private
 
 	def post_params
 		params.require(:post).permit(:title,:content,:image,:category,:season)
 	end
 
 	def set_post
 		@post = Post.find(params[:id])
 	end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  
 # def new
 # 	@register = Register.new(sign_up_params)
 # 	@register.is_editor = 0
 	#render 'new'
  #end

  private

  def sign_up_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :is_editor)
    #params[:is_editor] = 1
  end

  def account_update_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_navbar.html.erb
 <nav class="navbar navbar-default">
   <div class="container-fluid">
     <!-- Brand and toggle get grouped for better mobile display -->
     <div class="navbar-header">
       <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
         <span class="sr-only">Toggle navigation</span>
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
       </button>
       <a class="navbar-brand" href="#">Brand</a>
     </div>
 
     <!-- Collect the nav links, forms, and other content for toggling -->
     <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
       <ul class="nav navbar-nav navbar-right">
         <% if user_signed_in? %>
           <li><%= link_to "로그아웃", destroy_user_session_path, method: :delete %></li>
         <% else %>
           <li><%= link_to "로그인", new_user_session_path %></li>
         <% end %>
       </ul>
     </div><!-- /.navbar-collapse -->
   </div><!-- /.container-fluid -->
 </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Letter</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'style'%>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    <%= render 'layouts/navbar'  %>
    <div style="text-align:center"><h3><strong><%= link_to "LETTER", root_url%></strong></h3></div> 
	<%= yield %>
</body>
</html>

app/views/login/welcome.html.erb
<br></br>


<%= link_to "의", posts_wear_path, class: "btn btn-default" %>
<%= link_to "식", posts_eat_path, class: "btn btn-default" %>
<%= link_to "주", posts_live_path, class: "btn btn-default" %>
<%= link_to "락", posts_culture_path, class: "btn btn-default" %>

app/views/posts/_form.html.erb
 <%= simple_form_for @post do |f| %>
    <%= f.input :category, collection: Post.categories.keys, input_html: { :style=> 'width: 100px'} %>
    <%= f.input :season, collection: Post.seasons.keys, input_html: { :style=> 'width: 100px'} %>
    <%= f.text_field :title %>
    <br></br>
    <%= f.cktext_area :content %>
  	<%= f.submit %>
 <% end %>

 

app/views/posts/_index_form.html.erb
<table class="table table-striped">
	<thead>
		<tr>
			<th>제목</th>
			
		</tr>
	</thead>
	<tbody>
		<% @posts.each do |post| %>
				<tr>
						<td><%= link_to post.title, post%>

				</tr>
		<% end %>
	</tbody>
</table>

app/views/posts/culture.html.erb
<%= render 'posts/index_form' %>

app/views/posts/eat.html.erb
<%= render 'posts/index_form' %>

app/views/posts/edit.html.erb
<h3>글 수정하기</h3>
<%= render 'posts/form' %>
<%= link_to "돌아가기", posts_path, class: "btn btn-default" %>

app/views/posts/index.html.erb
<%= link_to "새 글 작성하기", new_post_path %>
<%= render 'posts/index_form' %>

app/views/posts/live.html.erb
<%= render 'posts/index_form' %>

app/views/posts/new.html.erb
<h3>새 글 작성하기</h3>
<%= render 'posts/form' %>
<br></br>
<%= link_to "돌아가기", posts_path, class: "btn btn-default" %>

app/views/posts/show.html.erb
<h3><%=@post.title%></h3>
<h5 style="text-align:right"><%=@post.created_at%></h5>
<p><%= @post.content.html_safe%></p>

<%= link_to "목록 |", posts_path %>
<%= link_to "편집 | ", edit_post_path %>
<%= link_to "삭제", post_path,
			method: :delete,
			data: {confirm: 'Are you sure?'} %>

app/views/posts/wear.html.erb
<%= render 'posts/index_form' %>